const appname = "T-Shopee Admin App",
    login = "Login",
    welcome = "Hi, Welcome to",
    email = "Email",
    password = "Password",
    forgotPassword = "Forgot Password ?",
    anyProblem = "In case of any difficulty, contact administration",
    credit = "@ntTung.code",
    dashboard = "Dashboard",
    rating = "Rating",
    totalSales = "Total Sales",
    popular = "Popular Products",
    unpaid = "Unpaid",
    shopSettings = "Shop Settings",
    messages = "Messages",
    logout = "Logout",
    changeImage = "Change Image",
    editProfile = " Edit Profile",
    orders = "Orders",
    products = "Products",
    settings = "Settings",
    featured = "Featured",
    edit = "Edit",
    remove = "Remove",
    save = "Save",
    chats = "Chats",
    confirmPass = "Confirm Password",
    name = "Username",
    loginTo = "Login to your account",
    emailHint = "nttung.code@gmail.com",
    passwordHint = "* * * * * *";

//shop settings

const nameHint = "Hi Tungnt",
      shopDescHint = " Enter your shop description",
      shopWebsiteHint = "tShopee.com",
      shopMobileHint = "+84384829738",
      shopAddressHint = "Hà Nội",
      description = "Description",
      mobile = "Shop Mobile",
      website = "Shop Website",
      shopName = "Shop Name",
      address = "Shop Address";

